### ISSUE TITLE
xcode warnings when building latest version

### ISSUE THREAD

**Issue by uddinr** [paypal/paypal-here-sdk-ios-distribution#248] opened 2018-07-10 17:17 UTC
i am using xcode 9.4.1 and i get the following warnings:

<img width="506" alt="screen shot 2018-07-10 at 18 15 34" src="https://user-images.githubusercontent.com/18418023/42526344-72ee8cb8-846d-11e8-9d51-ab11a4f59dd7.png">

with hardcoded paths of someone called robert?

**Comment by uddinr** [comment] 2018-07-30 12:30
is there any update to this?

**Comment by DJ92** [comment] 2018-07-30 13:55
Warnings don't block any builds as far as we've observed. If there are any build failures, please let us know with a new issues. Closing this for now.

**Closed by DJ92** 2018-07-30 13:55 UTC

**Comment by uddinr** [comment] 2018-07-30 14:06
indeed they do not block builds but they are warnings for a reason and shouldn't be ignored, the fact that there are hard coded paths rather than being ignored i believe these should be resolved.

**Comment by DJ92** [comment] 2018-07-30 14:59
Hey @uddinr, I have duly noted this as a feedback and we'll actively try to resolve it in our upcoming builds.

**Comment by uddinr** [comment] 2018-11-28 09:14
is there any progress on this?

**Comment by DJ92** [comment] 2018-11-28 14:54
Hey @uddinr , we did fix majority of them. You can try out the latest sample app and let us know if you have any concerns. Thanks.

**Comment by uddinr** [comment] 2018-11-28 15:59
doesn't seems to have been resolved, i get the warnings attached, i am also getting the warnings when running my app

<img width="884" alt="screenshot 2018-11-28 at 15 39 44" src="https://user-images.githubusercontent.com/18418023/49164172-82966000-f326-11e8-9667-27ed0cb5a658.png">
![screenshot 2018-11-28 at 15 57 30](https://user-images.githubusercontent.com/18418023/49164187-87f3aa80-f326-11e8-8bfb-e1e20d27e73b.png)

**Comment by uddinr** [comment] 2018-11-28 16:06
here is the output whilst building:

warning: /Users/robert/Library/Developer/Xcode/DerivedData/ModuleCache/5DA7UOIUSX73/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
note: while processing /Users/robert/Library/Developer/Xcode/DerivedData/ModuleCache/5DA7UOIUSX73/Foundation-3DFYNEBRQSXST.pcm
**note: Linking a static library that was built with -gmodules, but the module cache was not found.  Redistributable static libraries should never be built with module debugging enabled.  The debug experience will be degraded due to incomplete debug information.**
warning: /Users/robert/Library/Developer/Xcode/DerivedData/ModuleCache/5DA7UOIUSX73/ObjectiveC-1RQA2RIXJIE19.pcm: No such file or directory
note: while processing /Users/robert/Library/Developer/Xcode/DerivedData/ModuleCache/5DA7UOIUSX73/ObjectiveC-1RQA2RIXJIE19.pcm
warning: /Users/d500_macmini/Library/Developer/Xcode/DerivedData/ModuleCache/9ITOD1A8LC0C/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
note: while processing /Users/d500_macmini/Library/Developer/Xcode/DerivedData/ModuleCache/9ITOD1A8LC0C/Foundation-3DFYNEBRQSXST.pcm
warning: /Users/d500_macmini/Library/Developer/Xcode/DerivedData/ModuleCache/9ITOD1A8LC0C/CoreBluetooth-14O21S15A37HY.pcm: No such file or directory
note: while processing /Users/d500_macmini/Library/Developer/Xcode/DerivedData/ModuleCache/9ITOD1A8LC0C/CoreBluetooth-14O21S15A37HY.pcm
warning: /Users/d500_macmini/Library/Developer/Xcode/DerivedData/ModuleCache/9ITOD1A8LC0C/ObjectiveC-1RQA2RIXJIE19.pcm: No such file or directory
note: while processing /Users/d500_macmini/Library/Developer/Xcode/DerivedData/ModuleCache/9ITOD1A8LC0C/ObjectiveC-1RQA2RIXJIE19.pcm

**Comment by DJ92** [comment] 2018-11-28 16:47
Hey @uddinr , those look very specific to your own dependencies in the app while building. Can you try a pod clean install and see if it clears some of these?

**Comment by DJ92** [comment] 2018-11-28 21:10
Hey @uddinr , can you try this release version Pod -> PayPalHereSDKv2/Release ?

**Comment by DJ92** [comment] 2018-11-29 22:10
I'll take these to the team and see if we can fix some warnings due to dependencies but I wasn't able to reproduce any warnings or see any fatal issues.
